version: '3.2'
services:
  unifi-freeradius-ldap:
    build:
      dockerfile: Dockerfile
      context: .
    
    # don't have second level support on BASE_DOMAIN
    #image: haor/freeradius-google-ldap:latest
    env_file: env/freeradius.env
    volumes:
      - type: bind
        source: ./certs
        target: /certs
    network_mode: host
    
